name: check_in_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  uuid: ^4.4.2
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  hive_test: ^1.0.0


flutter:
  uses-material-design: true
